# Site settings
author: Amil Mašić
title: 52 Weeks
header-img: img/home-bg.png
email: amil.masic@gmail.com
copyright_name: Amil Mašić
description: > # this means to ignore newlines until "baseurl:"
  Attending Flatiron School Online Web Developer course.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AmilMasic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
